<?php

namespace App\Http\Requests\Fronend;

use App\Models\User;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Validation\Rule;

class PaymentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array|string>
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'email', 'max:255'],
            'phone' => ['sometimes', 'nullable', 'numeric', 'regex:/^(0[1-9][0-9]{8}|84[1-9][0-9]{8})$/'],
            'address' => ['required', 'string', 'max:255'],
            "note" => ['nullable', 'string', 'max:255']
            ,
            "province" => ['required', 'integer']
            ,
            "district" => ['required', 'integer']
            ,
            "ward" => ['required', 'integer']
        ];
    }


    public function messages()
    {
        return [
            'phone.regex' => "Số điện thoại chỉ bao gồm 10 số",
        ]; // TODO: Change the autogenerated stub
    }

}
