name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: 📂 Deploy to server via ssh
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.HOST_LARAVEL }}
        username: ${{ secrets.USERNAME_LARAVEL }}
        password: ${{ secrets.PASSWORD_LARAVEL }}
        port: ${{ secrets.PORT_SSH_LARAVEL }}
        script: "cd /home/eenelpah/nguyenthanhduy.id.vn && sh ./.scripts/deploy.sh"
        

